### ISSUE TITLE
Implement aut. tests for frontend interface

### ISSUE THREAD

**Issue by maximilianoertel** [LearnersBlock/learners-block#74] opened 2021-02-15 01:13 UTC
In order to improve the stability of future releases, the frontend interface should contain automated tests, i.e. using Jest and [Vue Test Utils ](https://vue-test-utils.vuejs.org/guides/)

**Comment by maggie0002** [comment] 2021-03-15 20:21
Duplicate of https://github.com/LearnersBlock/learners-block/issues/33

**Closed by maggie0002** 2021-03-15 20:21 UTC
Labels: enhancement, frontend, help wanted
